create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  created_at text not null,
  analyzed_at text not null,
  match_date text not null default '',
  home_team text not null,
  away_team text not null,
  algorithm_version text not null,
  source text not null default 'live_analysis',
  series_name text not null default 'validation-2.11',
  source_stats_json jsonb not null default '{}'::jsonb,
  config_snapshot_json jsonb,
  predicted_ht text,
  predicted_ft text,
  actual_ht_home integer,
  actual_ht_away integer,
  actual_ft_home integer,
  actual_ft_away integer,
  settled_at text,
  unique(match_date, home_team, away_team, algorithm_version, series_name)
);

create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  rule_id text not null,
  label text not null,
  selected_level text not null,
  passed boolean not null,
  raw_value double precision,
  threshold_value double precision,
  threshold_margin double precision,
  score double precision not null,
  data_quality double precision not null,
  mode text,
  selection_score double precision,
  reasons_json jsonb not null default '[]'::jsonb,
  odds_at_prediction double precision,
  bookmaker text,
  odds_captured_at text,
  closing_odds double precision,
  hit boolean,
  profit double precision,
  settled_at text,
  unique(match_id, rule_id)
);

create index if not exists idx_matches_version on public.matches(algorithm_version);
create index if not exists idx_matches_source on public.matches(source);
create index if not exists idx_matches_series on public.matches(series_name);
create index if not exists idx_recommendations_level on public.recommendations(selected_level);
create index if not exists idx_recommendations_rule on public.recommendations(rule_id);
create index if not exists idx_recommendations_hit on public.recommendations(hit);

alter table public.matches enable row level security;
alter table public.recommendations enable row level security;

-- The application uses SUPABASE_SERVICE_ROLE_KEY server-side, which bypasses RLS.
-- Never expose that key in browser code or commit it to the repository.
